Linux compole on Ubuntu 18.04

diff --git a/.github/workflows/Linux.yml b/.github/workflows/Linux.yml
--- a/.github/workflows/Linux.yml
+++ b/.github/workflows/Linux.yml
@@ -12,14 +12,9 @@ jobs:
 
   build:
 
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-18.04
     steps:
       - uses: actions/checkout@v2
-      #      - name: build_external
-      #        run: |
-      #          . setup.env
-      #          cd external/
-      #          ./build_external.sh Linux
 
       - name: before install
         run: |
@@ -27,23 +22,40 @@ jobs:
           sudo apt-get install -y yasm
           sudo apt-get install -y libsdl2-dev
           sudo apt-get install -y clang-format
+          sudo apt-get install git make gcc autoconf libtool yasm cmake g++ libsdl2-dev
           wget "https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz"
           tar zxf cmake-3.16.2-Linux-x86_64.tar.gz
           export PATH=`pwd`/cmake-3.16.2-Linux-x86_64/bin:$PATH
-          echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
+#          cmake
+#          echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
+          sudo apt-get install clang llvm
+          echo  1 |sudo update-alternatives --config cc #select clang
+
+      - name: build_external
+        run: |
+          . setup.env
+          cd external/
+          ./build_external.sh Linux
+      - name: build cmdline
+        run: |
+          cd cmdline/
+          mkdir build
+          cd build
+          cmake ../
+          make cicadaPlayer
 
 #      - name: before_script_judge
 #        if: ${{"$CHECK_FORMAT" == "ON" && "$TRAVIS_PULL_REQUEST" != "false"}}
 #        run:
 #          curl -L http://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py -o clang-format-diff.py;
 
-      - name: before_script
-        run: |
-          curl -L http://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py -o clang-format-diff.py;
-          . setup.env
-          cd external/
-          ./build_external.sh Linux
-          cd ../
+#      - name: before_script
+#        run: |
+#          curl -L http://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py -o clang-format-diff.py;
+#          . setup.env
+#          cd external/
+#          ./build_external.sh Linux
+#          cd ../
 
 #      - name: script_judge
 #        if: ${{"$CHECK_FORMAT" == "ON"}}
@@ -58,26 +70,18 @@ jobs:
 #              git diff -U0 --no-color HEAD^ | python ./clang-format-diff.py -p1 -i
 #              exit -1
 
-      - name: script
-        run: |
-          mkdir build
-          cd build
-          cmake -DCODE_COVERAGE=ON -DTRAVIS=ON -DUSEASAN=ON -DCMAKE_BUILD_TYPE=Debug ../
-          cmake --build . --config Debug -j8
-
-      - name: after_success
-        run: |
-          cd mediaPlayer/tests/
-          ctest -j8 --output-on-failure
-          bash <(curl -s https://codecov.io/bash) -x "llvm-cov gcov" || echo "Codecov did not collect coverage reports"
-          cd ../../framework/tests/
-          ctest -j8 --output-on-failure
-          bash <(curl -s https://codecov.io/bash) -x "llvm-cov gcov" || echo "Codecov did not collect coverage reports"
-
-#      - name: build cmdline
+#      - name: script
 #        run: |
-#          cd cmdline/
 #          mkdir build
 #          cd build
-#          cmake ../
-#          make cicadaPlayer
+#          cmake -DCODE_COVERAGE=ON -DTRAVIS=ON -DUSEASAN=ON -DCMAKE_BUILD_TYPE=Debug ../
+#          cmake --build . --config Debug -j8
+#
+#      - name: after_success
+#        run: |
+#          cd mediaPlayer/tests/
+#          ctest -j8 --output-on-failure
+#          bash <(curl -s https://codecov.io/bash) -x "llvm-cov gcov" || echo "Codecov did not collect coverage reports"
+#          cd ../../framework/tests/
+#          ctest -j8 --output-on-failure
+#          bash <(curl -s https://codecov.io/bash) -x "llvm-cov gcov" || echo "Codecov did not collect coverage reports"
